version: "3.7"
services:
  nginx:
    image: nginx:latest
    expose:
      - 80
    ports:
      - 80:80
    volumes:
      - ./templates/${NGINX_TEMPLATE:-default}:/etc/nginx/templates/
      - ./www:/data/static_web/
    environment:
      - HOSTNAME=${HOSTNAME}
